import type { Board, Player } from './checkWin';

export type ShapeKind = 'open-three' | 'four' | 'fork';

export interface DetectedShape {
  kind: ShapeKind;
  player: Player;
  cells: { row: number; col: number }[];
  dir: [number, number];
  key: string;
}

export interface MovePatternEvents {
  openThreesCreated: number;
  foursCreated: number;
  isFork: boolean;
  blocked: boolean; // placed on a critical open-end of an opponent threat
}

const DIRS: [number, number][] = [[0, 1], [1, 0], [1, 1], [1, -1]];

function shapeKey(
  player: Player,
  kind: ShapeKind,
  dr: number,
  dc: number,
  cells: { row: number; col: number }[],
): string {
  return `${player}:${kind}:${dr},${dc}:${cells.map(c => `${c.row},${c.col}`).join('|')}`;
}

function inBounds(r: number, c: number, size: number): boolean {
  return r >= 0 && r < size && c >= 0 && c < size;
}

/** All currently-active open-threes and fours on the board. */
export function detectActiveShapes(board: Board): DetectedShape[] {
  const size = board.length;
  const shapes: DetectedShape[] = [];

  for (const [dr, dc] of DIRS) {
    for (let r = 0; r < size; r++) {
      for (let c = 0; c < size; c++) {
        const player = board[r][c];
        if (!player) continue;

        // Only process from the canonical start of a run (cell before must not be same player).
        const pr = r - dr, pc = c - dc;
        if (inBounds(pr, pc, size) && board[pr][pc] === player) continue;

        // Count run length.
        let len = 1;
        while (
          inBounds(r + dr * len, c + dc * len, size) &&
          board[r + dr * len][c + dc * len] === player
        ) len++;

        if (len < 3 || len > 4) continue;

        const cells = Array.from({ length: len }, (_, i) => ({
          row: r + dr * i,
          col: c + dc * i,
        }));

        const beforeR = r - dr, beforeC = c - dc;
        const afterR = r + dr * len, afterC = c + dc * len;
        const beforeOpen = inBounds(beforeR, beforeC, size) && board[beforeR][beforeC] === null;
        const afterOpen = inBounds(afterR, afterC, size) && board[afterR][afterC] === null;

        if (len === 3 && beforeOpen && afterOpen) {
          const kind: ShapeKind = 'open-three';
          shapes.push({ kind, player, cells, dir: [dr, dc], key: shapeKey(player, kind, dr, dc, cells) });
        } else if (len === 4 && (beforeOpen || afterOpen)) {
          const kind: ShapeKind = 'four';
          shapes.push({ kind, player, cells, dir: [dr, dc], key: shapeKey(player, kind, dr, dc, cells) });
        }
      }
    }
  }

  return shapes;
}

/**
 * Analyse the events generated by placing `mover` at (moveRow, moveCol).
 * boardBefore must NOT contain the move; boardAfter must contain it.
 */
export function analyseMove(
  boardBefore: Board,
  boardAfter: Board,
  moveRow: number,
  moveCol: number,
  mover: Player,
): MovePatternEvents {
  const opponent: Player = mover === 'X' ? 'O' : 'X';

  const shapesBefore = detectActiveShapes(boardBefore);
  const shapesAfter = detectActiveShapes(boardAfter);

  const moverBefore = shapesBefore.filter(s => s.player === mover);
  const moverAfter = shapesAfter.filter(s => s.player === mover);
  const opponentBefore = shapesBefore.filter(s => s.player === opponent);

  const keysBefore = new Set(moverBefore.map(s => s.key));

  // New shapes for mover that involve the placed cell.
  const newShapes = moverAfter.filter(
    s => !keysBefore.has(s.key) && s.cells.some(c => c.row === moveRow && c.col === moveCol),
  );

  const openThreesCreated = newShapes.filter(s => s.kind === 'open-three').length;
  const foursCreated = newShapes.filter(s => s.kind === 'four').length;
  const isFork = newShapes.length >= 2;

  // Blocked threat: move landed on a critical open-end of an opponent shape.
  const blocked = opponentBefore.some(shape => {
    const [ddr, ddc] = shape.dir;
    const first = shape.cells[0];
    const last = shape.cells[shape.cells.length - 1];
    const bR = first.row - ddr, bC = first.col - ddc;
    const aR = last.row + ddr, aC = last.col + ddc;
    return (bR === moveRow && bC === moveCol) || (aR === moveRow && aC === moveCol);
  });

  return { openThreesCreated, foursCreated, isFork, blocked };
}

/**
 * Returns shapes newly created by the given move that qualify as a fork
 * (i.e., there are ≥2 of them). Empty array if not a fork.
 */
export function getForkShapes(
  boardBefore: Board,
  boardAfter: Board,
  moveRow: number,
  moveCol: number,
  mover: Player,
): DetectedShape[] {
  const moverBefore = detectActiveShapes(boardBefore).filter(s => s.player === mover);
  const moverAfter = detectActiveShapes(boardAfter).filter(s => s.player === mover);
  const keysBefore = new Set(moverBefore.map(s => s.key));

  const newShapes = moverAfter.filter(
    s => !keysBefore.has(s.key) && s.cells.some(c => c.row === moveRow && c.col === moveCol),
  );

  return newShapes.length >= 2 ? newShapes : [];
}
